//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.BranchBank = new HashSet<BranchBank>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public double UsdSell { get; set; }
        public double UsdBuy { get; set; }
        public double EurSell { get; set; }
        public double EurBuy { get; set; }
        public double RurSell { get; set; }
        public double RurBuy { get; set; }
    
        public virtual ICollection<BranchBank> BranchBank { get; set; }
    }
}
