//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.BranchBank = new HashSet<BranchBank>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateTime { get; set; }
        public decimal UsdSell { get; set; }
        public decimal UsdBuy { get; set; }
        public decimal EurSell { get; set; }
        public decimal EurBuy { get; set; }
        public decimal RurSell { get; set; }
        public decimal RurBuy { get; set; }
    
        public virtual ICollection<BranchBank> BranchBank { get; set; }
    }
}
